[project]
name = "test-task"
version = "0.1.0"
description = ""
authors = [
    {name = "zemchenko gennady",email = "zemchenkogennady@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "black (>=26.10.0,<27.0.0)",
    "ruff (>=0.16.10,<0.17.0)"
]
